### ISSUE TITLE
Can't get Fibonacci's example to work

### ISSUE THREAD

**Issue by dgmneto** [kkrawiec/swim#12]
Hello there,
I'm working in my graduation project and it's about code synthesis. I've been trying very hard to synthesize Fibonacci for a few days, but still couldn't get it to find a solution. I've tried to manipulate the example [here](https://github.com/kkrawiec/swim/blob/master/src/main/scala/swim/app/RecursiveInt.scala#L118) in any way that I could think of. Is there any hidden detail I should know of that will make it work?
Thank you very much for your time!!

**Comment by iwob** [comment]
Hello, synthesis of recursive functions is in general hard, especially for stochastic methods like genetic programming. It is very hard for the algorithm to come up with the both correct stop criterion and generated values. This creates a fitness plateau - there is no pressure towards improvement, since most of the solutions have the worst fitness. And there is no easy way out, I'm afraid - as far as I know an efficient synthesis of recursive functions with GP is still an open research problem.

**Comment by dgmneto** [comment]
Ooh, I see. Thank you very much for your fast response.
I just wanted to be sure the example in the repo wasn't intended to find a solution. 
I'll close this issue now; feel free to reopen it if there is more to discuss

**Comment by JerrySwan** [comment]
>as far as I know an efficient synthesis of recursive functions with GP is
still an open research problem.
Here's a recent paper that shows that stochastic synthesis of recursive
functions can be done easily, if one uses the right 'template' for the
recursion:
https://link.springer.com/article/10.1007/s10710-019-09347-3

Best wishes,

Jerry.
